project:
  type: book

book:
  title: "Apunte de Cálculo Numérico - FIQ - UNL"
  author:
    - Marcelo Actis
    - Agustin Ostrosky Umedez
  chapters:
    - index.qmd
    - chapters/00-python.qmd
    - chapters/01-no-lineales.qmd
    - chapters/02-interpolacion.qmd
    - chapters/03-integracion.qmd
    - chapters/04-pvi.qmd
    - chapters/05-diferencias-finitas.qmd

bibliography: references.bib

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    theme: cosmo
    code-fold: true
    smooth-scroll: true
    html-math-method: katex
