project:
  type: book
  output-dir: _book

book:
  title: "Apunte de Cálculo Numérico"
  subtitle: "FIQ - UNL"
  author:
    - Marcelo Actis
    - Agustín Ostrosky Umedez
  
  date: today
  
  chapters:
    - index.qmd
    - part: "Preliminares"
      chapters:
        - chapters/01-intro.qmd
    - part: "Parte I"
      chapters:
        - chapters/02-no-lineales.qmd
        - chapters/03-interpolacion.qmd
        - chapters/04-integracion.qmd
    - part: "Parte II"
      chapters:
        - chapters/05-pvi.qmd
        - chapters/06-diferencias-finitas.qmd

bibliography: references.bib

execute:
  enabled: true
  freeze: auto
  echo: true
  warning: false
  message: false
  cache: true
  python: .venv/bin/python

format:
  live-html:
    grid:
      sidebar-width: 225px
      margin-width: 225px
      body-width: 850px
    theme:
      light: [cosmo, styles/quick-tools.scss, styles/custom-theme.scss]
      dark:  [cosmo, styles/quick-tools.scss, styles/custom-theme.scss, styles/theme-dark.scss]
    toc: true
    toc-depth: 4
    number-sections: true
    number-depth: 3
    code-fold: show
    code-summary: "Mostrar código"
    code-copy: true
    smooth-scroll: true
    # html-math-method: katex
    respect-user-color-scheme: true

lang: es

language:
  callout-tip-title: ""
  crossref:
    eq-prefix: "Ecuación"
    thm-prefix: "Teorema"
    fig-prefix: "Figura"