---
title: "Integración numérica o cuadratura"
---
{{< include ../_macros.qmd >}}

El objetivo de este capítulo es hallar fórmulas que permitan calcular integrales (aproximadas) pero de cualquier función. Cuando decimos *aproximadas* queremos decir con tanta precisión como se desee.

Queremos calcular por ejemplo
$$
\int_0^A e^{-x^2} \, dx \qquad\text{o} \qquad
\int_6^5 \frac{t^3}{e^t-1} \dd t
$$
que no tienen una expresión analítica.

Integrales difíciles de resolver analíticamente suelen aparecer al calcular el área de superficies de revolución.

Recordamos que el área de la superficie de revolución que se obtiene al girar el gráfico de $y = f(x)$ alrededor del eje $x$, para $a \le x \le b$ es
$$
\int_a^b 2\pi f(x) \sqrt{1+f'(x)^2} \dd x.
$$
Rara vez el integrando de esta expresión se podrá integrar analíticamente, y son muy útiles los métodos numéricos. Estos no nos dan una fórmula cerrada para el resultado, pero permiten calcular la integral con tanta precisión como se desee.


## Fórmulas de Newton-Côtes {#sec:for.new.cotes}

Supongamos que se desea calcular la integral
$$
\int_a^b f(x) \dd x
$$
para una función dada $f$.

La idea de las fórmulas de Newton-Côtes es interpolar la función $f$ en $n$ puntos equiespaciados con un polinomio de grado $\le n-1$ e integrar el polinomio.

Por ejemplo, para $n=1$ tomamos el punto medio, y el polinomio de grado cero que interpola en ese punto es la función constante $p_1(x) = f(\frac{a+b}2)$. Resulta
$$
\int_a^b f(x) \, dx \approx \int_a^b p_1(x) \dd x = \int_a^b f(\frac{a+b}2) \dd x
= \underbrace{(b-a)f(\frac{a+b}2)}_{Q_1(f;a,b)}.
$$
Esta fórmula se conoce como *Regla del rectángulo*, porque estamos calculando el área del rectángulo con base $(b-a)$ y altura $f(\frac{a+b}2)$.

Para $n=2$ podemos escribir el polinomio $p_2$ que interpola a $f$ en $x=a$ y en $x=b$ de la siguiente manera:
$$
p_2(x) = \frac{b-x}{b-a} f(a) + \frac{x-a}{b-a} f(b).
$$
Luego,
$$
\int_a^b f(x) \, dx \approx \int_a^b p_2(x) \dd x
= \dots = \underbrace{ (b-a) \left( \frac12 f(a) + \frac12 f(b) \right)}_{Q_2(f;a,b)}.
$$
Esta fórmula se conoce como *Regla del trapecio*, porque estamos calculando el área del trapecio con bases $f(a)$, $f(b)$ y altura $(b-a)$.

Para $n=3$ podemos escribir el polinomio $p_3$ que interpola a $f$ en $x=a$, $x=m=\frac{a+b}2$ y en $x=b$ de la siguiente manera:
$$
p_3(x) = \frac{(b-x)(m-x)}{(b-a)(m-a)} f(a) + \frac{(b-x)(a-x)}{(b-m)(a-m)} f(m)
+ \frac{(x-a)(x-m)}{(b-a)(b-m)} f(b).
$$
Luego,
$$
\int_a^b f(x) \, dx \approx \int_a^b p_3(x) \dd x
= \dots = \underbrace{(b-a) \left( \frac16 f(a) + \frac46 f(m) + \frac16 f(b) \right)}_{Q_3(f;a,b)}.
$$
Esta fórmula se conoce como *Regla de Simpson*.

Las operaciones que no escribimos y que irían en $\cdots$ son muy laboriosas.
Lo importante de entender aquí son dos cosas:

1. Las fórmulas de integración numérica consisten en evaluar $f$ en distintos puntos del intervalo, multiplicar esos valores por otros números, sumar, y finalmente multiplicar por la longitud del intervalo.

2. Las fórmulas deberían ser exactas cuando se la aplicamos a un polinomio $p$ de grado $\le n-1$, es decir:

    $$
    \int_a^b p(x) \dd x = Q_n (p,a,b)
    $$

    ¿Por qué? Porque si interpolamos un polinomio de grado $\le n-1$ en $n$ puntos, obtenemos el mismo polinomio original. Entonces integrar ese polinomio nos da la integral de la función de partida.

:::: {.callout-warning title="Fórmula de integración numérica o de cuadratura"}

::: {#def-formula.int.num.o.cuad}
Una **fórmula de integración numérica o de cuadratura** consiste de $n$ puntos $x_1$, $x_2$, $\dots$, $x_n$ en el intervalo y $n$ *pesos* $w_1$, $w_2$, $\dots$, $w_n$ de modo que
$$
\int_a^b f(x) \, dx \approx (b-a) \sum_{i=1}^n w_i f(x_i) =: Q_n(f;a,b).
$$
:::

::::

Para hallar los $w_i$ correspondientes a la fórmula de Newton-Côtes de $n$ puntos, consideramos el intervalo $[0,1]$ y recordamos que debería cumplirse que para todo polinomio de grado $\le n-1$
$$
\int_a^b p(x) \, dx = Q_n (p;a,b) = \sum_{i=1}^n w_i p(x_i).
$$

En particular debería cumplirse para $p_0(x) = 1$, para $p_1(x) = x$, para $p_2(x) = x^2$, $\dots$, y para $p_{n-1}(x) = x^{n-1}$.

Luego
$$
\begin{align*}
p_0(x) &= 1 & \int_0^1 1\, dx = 1 &= w_1 + w_2 + \dots + w_n\\
p_1(x) &= x & \int_0^1 x\, dx = \frac12 &= w_1 x_1 + w_2 x_2 + \dots + w_n x_n\\
p_2(x) &= x^2 & \int_0^1 x^2\, dx = \frac13 &= w_1 x_1^2 + w_2 x_2^2 + \dots + w_n x_n^2\\
&\vdots \\
p_{n-1}(x) &= x^{n-1} & \int_0^1 x^{n-1}\, dx = \frac1n &= w_1 x_1^{n-1} + w_2 x_2^{n-1} + \dots + w_n x_n^{n-1}.
\end{align*}
$$

Tomando los puntos $x_1,\dots,x_n$ equiespaciados en $[0,1]$, es decir, $x_1 = 0$, $x_2 = 1/(n-1)$, $x_3 = 2/(n-1)$ $\dots$, $x_n = 1$ (`x=np.linspace(0,1,n)`), sólo nos queda determinar los pesos $w_i$ de la fórmula. Entonces vemos que los pesos $w_i$ son las soluciones del siguiente sistema de ecuaciones
$$
\begin{align*}
  w_1 + w_2 + \dots + w_n &= 1\\
w_1 x_1 + w_2 x_2 + \dots + w_n x_n &= \frac12\\
 w_1 x_1^2 + w_2 x_2^2 + \dots + w_n x_n^2 &= \frac13\\
&\,\,\vdots \\
w_1 x_1^{n-1} + w_2 x_2^{n-1} + \dots + w_n x_n^{n-1}&= \frac1n.
\end{align*}
$$

En forma matricial
$$
\begin{bmatrix}
1 & 1 &  \dots & 1 \\
x_1 & x_2 & \dots & x_n \\
x_1^2 & x_2^2 & \dots & x_n^2 \\
&\vdots \\
x_1^{n-1} & x_2^{n-1} & \dots & x_n^{n-1}
\end{bmatrix}
\begin{bmatrix}
w_1 \\ w_2 \\ \vdots \\ w_n
\end{bmatrix}
=
\begin{bmatrix}
1 \\ \frac12 \\ \vdots \\ \frac1n
\end{bmatrix}
$$

Por lo tanto, los pesos de la fórmula de Newton-Côtes se encuentran resolviendo ese sistema.

Existen otras maneras de hallar los pesos que son más precisas si $n$ es grande, pero para $n\le 10$ (que es lo que utilizaremos nosotros), esta manera es práctica.

El siguiente código calcula, dado un entero positivo $n$, los pesos $w_i$ tomando las abscisas $x_i$ equiespaciadas en el intervalo $[0,1]$.
```{python}
#| code-fold: false

import numpy as np

def pesosNC(n):
    # Calcula los pesos de la fórmula de Newton-Cotes de n puntos
    x = np.linspace(0, 1, n)
    A = np.ones((n, n))
    for i in range(1, n):
        A[i, :] = A[i-1, :] * x
    b = 1 / np.arange(1, n+1)
    w = np.linalg.solve(A, b)
    return w
```

El siguiente código calcula la integral aproximada de una función $f$ utilizando la fórmula de Newton-Côtes de $n$ puntos. Las abscisas se calculan tomando $n$ puntos equiespaciados en el intervalo $[a,b]$ (usando `np.linspace`).
```{python}
#| code-fold: false

import numpy as np

def integralNC(f,a,b,n):
    w = pesosNC(n)
    x = np.linspace(a,b,n)
    y = f(x)
    Q = (b - a)*np.sum(y * w)
    return Q
```

::: {#des-int.newton.cotes .callout-tip icon="false"}
## 📝 Desafío 1
Compruebe su funcionamiento integrando $f(x)=\sin(x)$ en el $[0,\pi]$ tanto analíticamente como numéricamente usando `integralNC` para diferentes $n$.
:::

## Análisis del error para las fórmulas de Newton-Côtes {#sec-an.error.for.new.cotes}
Dada una función suave $f$ en el intervalo $[a,b]$, ¿Qué error se comete al calcular la integral con la fórmula de Newton-Côtes de $n$ puntos?

Para saber esto, recordemos que

$$
Q_n(f;a,b) = \int_a^b p_n(x) \dd x
$$

con $p_n$ el polinomio de grado $\le n-1$ que interpola a $f$ en $n$ puntos.
Este polinomio satisface, según el Corolario 2.7 del capítulo anterior

$$
\max_{x\in[a,b]} |f(x)-p_n(x)| \le \frac{M_n}{n} \frac{|b-a|^n}{(n-1)^n},
$$

con $M_n = \max_{\xi\in[a,b]} |f^n(\xi)|$.

Por lo tanto


\begin{align*}
\left| \int_a^b f(x) \dd x - Q_n(f;a,b) \right|
&= \left| \int_a^b f(x) \dd x - \int_a^b p_n(x) \dd x \right|
\\
&= \left| \int_a^b f(x) -p_n(x) \dd x  \right|
\le \int_a^b |f(x) -p_n(x)| \dd x
\\
&\le |b-a| \frac{M_n}{n} \frac{|b-a|^n}{(n-1)^n}
= \frac{M_n}{n} \frac{|b-a|^{n+1}}{(n-1)^n}
\end{align*}

Hemos demostrado entonces el siguiente teorema.

:::: {.callout-warning icon="false"}
## Error de Cuadratura

::: {#thm-error.cuadratura}
Si $f$ es una función $C^{n}$ en $[a,b]$, entonces
$$
\left|\int_a^b f(x) \,dx - Q_n(f;a,b) \right|
\le \frac{M_{n} |b-a|^{n+1}}{n (n-1)^n},
$$
con $M_n = \max_{\xi\in[a,b]} |f^n(\xi)|$.
:::

::::

Esta cota del error entre la integral exacta y la aproximada tiene el mismo problema que la cota del error de interpolación. Hay muchas funciones para las que ese término **no** tiende a cero (cuando $M_n \to \infty$ rápidamente.) Este problema se resuelve utilizando las fórmulas de Newton-Côtes compuestas que veremos en la siguiente sección.

### Pongámonos a prueba!!! 💪🏻

Intentá hallar la solución a los siguientes problemas con los conocimientos adquiridos en esta sección.

Recordá que si bien estás buscando un resultado en particular, herramientas como gráficas u otros cálculos auxiliares pueden ser de mucha ayuda para llegar a este.

Podés resolver utilizando la celda de código dispuesta luego de los ejercicios en este mismo apunte, o corriendo python de manera local.

:::: {.callout-tip icon="false" collapse="false"}
## 📝 Ejercicio Error Newton-Côtes 1

::: {}
Para cada una las siguientes funciones $f$, calcule a mano la integral de $f$, $I(f,0,5) = \int_0^5 f(x) \dd x$, las aproximaciones dadas por la regla del trapecio $Q_2(f,0,5)$ y de Simpson $Q_3(f,0,5)$, y los errores asociados a ambas aproximaciones. Explique los resultados.

$$
f(x) = -2x + 1.
$$
$$
f(x) = 3.5 x^2 + 2 x - 56.
$$
$$
f(x) = -1.5 x^3 - x^2 + 7.6.
$$
:::

```{pyodide-python}
# Use esta celda sólo en caso de no disponer de Spyder en este momento




```
::::

:::: {.callout-tip icon="false" collapse="true"}
## 📝 Ejercicio Error Newton-Côtes 2

::: {}
Recordemos que $Q_n(f,a,b)$ denota la fórmula de Newton-Cotes de $n$ puntos en el intervalo $[a,b]$.

1. Completar los siguientes cuadros y verificar si el error entre $\int_a^b f(x) \dd x$ y $Q_n(f,a,b)$ tiende a cero a medida que $n$ crece.

    $f(x) = \sin(\pi x)$, en $[a,b]= [0,5]$

    | $n$ | $\int_{0}^5 f(x)dx - Q_n(f,0,5)$ |
    |:--:|:--:|
    | 2 |  |
    | 3 |  |
    | $\vdots$ |  |
    | 12 |  |
    | 13 |  |

    <br>
    $f(x) = \frac{1}{1+x^2}$, en $[a,b]= [-5,5]$

    | $n$ | $\int_{-5}^5 f(x)dx - Q_n(f,-5,5)$ |
    |:--:|:--:|
    | 2 |  |
    | 3 |  |
    | $\vdots$ |  |
    | 12 |  |
    | 13 |  |

*Sugerencia: Para analizar tablas de errores lo más importante son los dos primeros dígitos significativos del error y su magnitud, no hace falta escribir tantos dígitos.*

2. Para cada una de las funciones del item anterior, realizar el gráfico de $f$ y de los polinomios interpolantes en $n$ puntos equidistribuidos del intervalo $[a,b]$, para los valores de $n$ en la tabla. Relacionar los resultados del item anterior con los gráficos obtenidos.

3. ¿Es cierto que $\lim_{n\to\infty} Q_n(f,a,b) =  \int_a^b f(x) \dd x$, para toda función $f$?
:::

```{pyodide-python}
# Use esta celda sólo en caso de no disponer de Spyder en este momento




```
::::


## Fórmulas de Newton-Côtes compuestas {#sec-for.new.cotes.comp}
La idea principal de estas fórmulas es integrar en lugar del interpolante polinomial de todo el intervalo un interpolante polinomial a trozos.

Particionamos el intervalo $[a,b]$ en $L$ sub-intervalos de longitud $h = \dfrac{b-a}L$. Definimos
$$
z_1 = a, \quad z_2 = a+h, \quad z_3 = a+2h, \quad\dots\quad
z_L = a+(L-1)h = b-h, \quad z_{L+1} = a+Lh = b,
$$
y observamos que
$$
\int_a^b f(x) \dd x = \int_{z_1}^{z_2} f(x) \dd x + \int_{z_2}^{z_3} f(x) \dd x + \dots
+ \int_{z_{L}}^{z_{L+1}} f(x) \dd x
= \sum_{i=1}^L \int_{z_i}^{z_{i+1}} f(x) \dd x.
$$
Luego, aproximamos cada integral con una fórmula de Newton-Côtes con $n$ fijo, es decir
$$
\int_{z_i}^{z_{i+1}} f(x) \dd x
\approx Q_n(f,z_i,z_{i+1})
$$
y resulta
$$
\int_a^b f(x) \dd x
\approx \sum_{i=1}^L Q_n(f,z_i,z_{i+1})=:Q_n^L(f;a,b).
$$

Para calcular una integral con este método, podemos usar el siguiente código:
```{python}
def NCcompuesta(f,a,b,L,n):
    " function Q = NCcompuesta(f,a,b,L,n)"
    " aproxima la integral de f sobre [a,b]"
    " utilizando la formula de Newton-Cotes compuesta"
    " de n puntos, subdividiendo en L subintervalos"
    y = np.linspace(a, b, L + 1)
    Q = 0
    for i in range(L):
        Q = Q + integralNC(f, y[i], y[i + 1], n)
    return Q
```

Esta implementación es muy ineficiente, pues cada vez que se llama a `integralNC` se calculan los pesos de Newton-Côtes, y estos son los mismos en todos los sub-intervalos. La siguiente, es una implementación un poco más eficiente:
```{python}
def intNCcompuesta(f, a, b, L, n):
    z = np.linspace(a, b, L + 1)
    h = (b - a) / L
    w = pesosNC(n)
    Q = 0
    for i in range(L):
        x = np.linspace(z[i], z[i + 1], n)
        y = f(x)
        Q += h * np.sum(y * w)
    return Q
```

::: {.callout}
## Observación
La fórmula compuesta correspondiente a $n=2$ se llama *fórmula del trapecio compuesta* y la correspondiente a $n=3$ se llama *fórmula de Simpson compuesta*.
:::




